<a href="https://colab.research.google.com/github/HarshNA044/machine-learning-practice/blob/main/linear%20regression/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data sourced from [Exploratory-Data-Analysis-EDA--Retail-Sales-Data Repository](https://github.com/tejas79883/Exploratory-Data-Analysis-EDA--Retail-Sales-Data)**. Details in data/about_data.md

**Direct CSV Link:** https://raw.githubusercontent.com/tejas79883/Exploratory-Data-Analysis-EDA--Retail-Sales-Data/main/Retail.csv

In [ ]:
import pandas as pd

In [ ]:
# importing dataset
url = "https://raw.githubusercontent.com/tejas79883/Exploratory-Data-Analysis-EDA--Retail-Sales-Data/main/Retail.csv"
data = pd.read_csv(url)

In [ ]:
df=pd.DataFrame(data)

In [ ]:
# first 5 rows
df.head()

,OrderNumber,ProductName,Color,Category,Subcategory,ListPrice,Orderdate,Duedate,Shipdate,PromotionName,SalesRegion,OrderQuantity,UnitPrice,SalesAmount,DiscountAmount,TaxAmount,Freight
0,SO43843,"Mountain-100 Silver, 48",Silver,Bikes,Mountain Bikes,3399.9900,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,2039.9940,4079.9880,0.0,326.3990,101.9997
1,SO43843,"Mountain-100 Black, 48",Black,Bikes,Mountain Bikes,3374.9900,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,2024.9940,4049.9880,0.0,323.9990,101.2497
2,SO43843,"HL Mountain Frame - Silver, 46",Silver,Components,Mountain Frames,1204.3248,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,722.5949,1445.1898,0.0,115.6152,36.1297
3,SO43843,"Mountain-100 Black, 44",Black,Bikes,Mountain Bikes,NaN,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,5,2024.9940,10124.9700,0.0,809.9976,253.1243
4,SO43843,"HL Mountain Frame - Silver, 38",Silver,Components,Mountain Frames,1204.3248,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,722.5949,1445.1898,0.0,115.6152,36.1297

In [ ]:
# size of dataframe (rows X columns)
df.shape

(32040, 17)

In [ ]:
# all column names
df.columns

Index(['OrderNumber', 'ProductName', 'Color', 'Category', 'Subcategory',
       'ListPrice', 'Orderdate', 'Duedate', 'Shipdate', 'PromotionName',
       'SalesRegion', 'OrderQuantity', 'UnitPrice', 'SalesAmount',
       'DiscountAmount', 'TaxAmount', 'Freight'],
      dtype='object')

In [ ]:
# provides a concise summary of a dataset, showing total rows, column names, non-missing value counts, data types, and memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32040 entries, 0 to 32039
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderNumber     32040 non-null  object
 1   ProductName     32040 non-null  object
 2   Color           29073 non-null  object
 3   Category        32040 non-null  object
 4   Subcategory     32040 non-null  object
 5   ListPrice       32032 non-null  float64
 6   Orderdate       32040 non-null  object
 7   Duedate         32040 non-null  object
 8   Shipdate        32040 non-null  object
 9   PromotionName   32040 non-null  object
 10  SalesRegion     32025 non-null  object
 11  OrderQuantity   32026 non-null  object
 12  UnitPrice       32040 non-null  float64
 13  SalesAmount     32040 non-null  float64
 14  DiscountAmount  32040 non-null  float64
 15  TaxAmount       32040 non-null  float64
 16  Freight         32040 non-null  float64
dtypes: float64(6), object(11)
memory usage: 4.2+ MB

# Basic Data Cleaning

## Copying Dataframe
We copy a DataFrame—usually using df_cleaned = df.copy()—to protect the original raw data from accidental alterations during the cleaning and preprocessing phases.

- **Creates a Safety Net**: If you make a mistake while cleaning data (like accidentally wiping out a column or filling missing values incorrectly), you can easily revert to the original DataFrame without having to re-download or re-load the raw dataset into memory.

- **Prevents SettingWithCopyWarning**: Pandas often flags a warning when you modify a sliced portion of a DataFrame instead of an explicit copy. Creating a dedicated copy tells Pandas to create a brand new, independent object in your computer's memory, avoiding this common error.

- **Preserves the Audit Trail**: Keeping a copy allows you to compare your "before" and "after" datasets side-by-side during your Exploratory Data Analysis (EDA) to verify that your transformations worked exactly as intended.

In [ ]:
df

,OrderNumber,ProductName,Color,Category,Subcategory,ListPrice,Orderdate,Duedate,Shipdate,PromotionName,SalesRegion,OrderQuantity,UnitPrice,SalesAmount,DiscountAmount,TaxAmount,Freight
0,SO43843,"Mountain-100 Silver, 48",Silver,Bikes,Mountain Bikes,3399.9900,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,2039.9940,4079.9880,0.0,326.3990,101.9997
1,SO43843,"Mountain-100 Black, 48",Black,Bikes,Mountain Bikes,3374.9900,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,2024.9940,4049.9880,0.0,323.9990,101.2497
2,SO43843,"HL Mountain Frame - Silver, 46",Silver,Components,Mountain Frames,1204.3248,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,722.5949,1445.1898,0.0,115.6152,36.1297
3,SO43843,"Mountain-100 Black, 44",Black,Bikes,Mountain Bikes,NaN,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,5,2024.9940,10124.9700,0.0,809.9976,253.1243
4,SO43843,"HL Mountain Frame - Silver, 38",Silver,Components,Mountain Frames,1204.3248,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,722.5949,1445.1898,0.0,115.6152,36.1297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32035,SO61267,"Touring-1000 Blue, 60",Blue,Bikes,Touring Bikes,2384.0700,6/30/2013,07-12-2013,07-07-2013,No Discount,Northwest,2,1430.4420,2860.8840,0.0,228.8707,71.5221
32036,SO61267,"Touring-2000 Blue, 60",Blue,Bikes,Touring Bikes,1214.8500,6/30/2013,07-12-2013,07-07-2013,No Discount,Northwest,1,728.9100,728.9100,0.0,58.3128,18.2228
32037,SO61267,"HL Touring Frame - Blue, 60",Blue,Components,Touring Frames,1003.9100,6/30/2013,07-12-2013,07-07-2013,No Discount,Northwest,2,602.3460,1204.6920,0.0,96.3754,30.1173
32038,SO61267,"Touring-2000 Blue, 54",Blue,Bikes,Touring Bikes,1214.8500,6/30/2013,07-12-2013,07-07-2013,No Discount,Northwest,2,728.9100,1457.8200,0.0,116.6256,36.4455
32039,SO61268,"LL Touring Frame - Yellow, 50",Yellow,Components,Touring Frames,333.4200,6/30/2013,07-12-2013,07-07-2013,No Discount,Southwest,3,200.0520,600.1560,0.0,48.0125,15.0039

In [ ]:
df_cleaned = df.copy()

In [ ]:
df_cleaned

,OrderNumber,ProductName,Color,Category,Subcategory,ListPrice,Orderdate,Duedate,Shipdate,PromotionName,SalesRegion,OrderQuantity,UnitPrice,SalesAmount,DiscountAmount,TaxAmount,Freight
0,SO43843,"Mountain-100 Silver, 48",Silver,Bikes,Mountain Bikes,3399.9900,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,2039.9940,4079.9880,0.0,326.3990,101.9997
1,SO43843,"Mountain-100 Black, 48",Black,Bikes,Mountain Bikes,3374.9900,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,2024.9940,4049.9880,0.0,323.9990,101.2497
2,SO43843,"HL Mountain Frame - Silver, 46",Silver,Components,Mountain Frames,1204.3248,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,722.5949,1445.1898,0.0,115.6152,36.1297
3,SO43843,"Mountain-100 Black, 44",Black,Bikes,Mountain Bikes,NaN,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,5,2024.9940,10124.9700,0.0,809.9976,253.1243
4,SO43843,"HL Mountain Frame - Silver, 38",Silver,Components,Mountain Frames,1204.3248,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,722.5949,1445.1898,0.0,115.6152,36.1297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32035,SO61267,"Touring-1000 Blue, 60",Blue,Bikes,Touring Bikes,2384.0700,6/30/2013,07-12-2013,07-07-2013,No Discount,Northwest,2,1430.4420,2860.8840,0.0,228.8707,71.5221
32036,SO61267,"Touring-2000 Blue, 60",Blue,Bikes,Touring Bikes,1214.8500,6/30/2013,07-12-2013,07-07-2013,No Discount,Northwest,1,728.9100,728.9100,0.0,58.3128,18.2228
32037,SO61267,"HL Touring Frame - Blue, 60",Blue,Components,Touring Frames,1003.9100,6/30/2013,07-12-2013,07-07-2013,No Discount,Northwest,2,602.3460,1204.6920,0.0,96.3754,30.1173
32038,SO61267,"Touring-2000 Blue, 54",Blue,Bikes,Touring Bikes,1214.8500,6/30/2013,07-12-2013,07-07-2013,No Discount,Northwest,2,728.9100,1457.8200,0.0,116.6256,36.4455
32039,SO61268,"LL Touring Frame - Yellow, 50",Yellow,Components,Touring Frames,333.4200,6/30/2013,07-12-2013,07-07-2013,No Discount,Southwest,3,200.0520,600.1560,0.0,48.0125,15.0039

## Removing Duplicate Rows

In [ ]:
# which row is duplicated
df_cleaned.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32035    False
32036    False
32037    False
32038    False
32039    False
Length: 32040, dtype: bool

In [ ]:
# sum of all duplicated rows
df_cleaned.duplicated().sum()

# dropping duplicated rows
# df_cleaned = df_cleaned.drop_duplicates()

# in our case 0 dupicated rows are there

np.int64(0)

## Removing Irrelevant Columns

In [ ]:
df_cleaned.head()

,OrderNumber,ProductName,Color,Category,Subcategory,ListPrice,Orderdate,Duedate,Shipdate,PromotionName,SalesRegion,OrderQuantity,UnitPrice,SalesAmount,DiscountAmount,TaxAmount,Freight
0,SO43843,"Mountain-100 Silver, 48",Silver,Bikes,Mountain Bikes,3399.9900,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,2039.9940,4079.9880,0.0,326.3990,101.9997
1,SO43843,"Mountain-100 Black, 48",Black,Bikes,Mountain Bikes,3374.9900,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,2024.9940,4049.9880,0.0,323.9990,101.2497
2,SO43843,"HL Mountain Frame - Silver, 46",Silver,Components,Mountain Frames,1204.3248,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,722.5949,1445.1898,0.0,115.6152,36.1297
3,SO43843,"Mountain-100 Black, 44",Black,Bikes,Mountain Bikes,NaN,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,5,2024.9940,10124.9700,0.0,809.9976,253.1243
4,SO43843,"HL Mountain Frame - Silver, 38",Silver,Components,Mountain Frames,1204.3248,1/29/2011,02-10-2011,02-05-2011,No Discount,Central,2,722.5949,1445.1898,0.0,115.6152,36.1297

### Manual Feature Selection (or Domain-Knowledge-Based Feature Selection)
Our target variable is SalesAmount. To build a mathematically sound linear regression model, we must select our independent variables ($X$) based on a core machine learning rule: The model can only look at information known before the transaction takes place.
#### 1. Columns to KEEP (Model Features)

* **ListPrice**: The baseline sticker price on the shelf. This provides the primary linear anchor for calculating final sales revenue.
* **Category & Subcategory**: Captures product tier definitions (e.g., Bikes vs Mountain Bikes), setting baseline value expectations.
* **Color**: Accounts for consumer aesthetic preferences that might sway demand or premium pricing.
* **PromotionName**: Captures marketing impacts (e.g., Black Friday deals), which heavily drive fluctuations in transaction totals.
* **SalesRegion**: Accounts for geographic purchasing power and regional demand differences.
* **Orderdate**: Extracted into Order_Month and Order_DayOfWeek to capture seasonal trends and weekend spikes.

#### 2. Columns to DROP (Data Leakage / Cheating)

* **TaxAmount & DiscountAmount**: These are calculated directly from or alongside the final SalesAmount. Leaving them in causes data leakage; the model will simply "reverse-engineer" the math instead of learning real customer behavior.
* **UnitPrice & OrderQuantity**: In pure arithmetic, $UnitPrice \times Quantity = SalesAmount$. Providing both forces the model to memorize a basic multiplication formula rather than build predictive intelligence.
* **Freight**: Shipping and backend logistic costs are determined only after items are weighed and boxed post-sale.

#### 3. Columns to DROP (Administrative & Irrelevant Labels)

* **OrderNumber**: A random tracking string database ID with zero numerical relationship to pricing.
* **ProductName**: We drop ProductName because a linear regression model is just a calculator that only understands numbers, not text. However, converting thousands of unique product names into numeric columns would overwhelm the computer, slow down training, and cause the model to overfit (memorize specific items instead of learning general trends). By dropping the individual names and keeping broader columns like Category, we keep the dataset clean, efficient, and ready for mathematical modeling.
* **Duedate & Shipdate**: Backend operational and delivery timestamps that occur after checkout and do not drive consumer buying decisions.

In [ ]:
# dropping irrelevant features
df_cleaned = df_cleaned.drop(columns=['TaxAmount', 'DiscountAmount', 'UnitPrice', 'OrderQuantity', 'Freight', 'OrderNumber', 'ProductName', 'Duedate', 'Shipdate'], axis='columns')

In [ ]:
df_cleaned.head()

,Color,Category,Subcategory,ListPrice,Orderdate,PromotionName,SalesRegion,SalesAmount
0,Silver,Bikes,Mountain Bikes,3399.9900,1/29/2011,No Discount,Central,4079.9880
1,Black,Bikes,Mountain Bikes,3374.9900,1/29/2011,No Discount,Central,4049.9880
2,Silver,Components,Mountain Frames,1204.3248,1/29/2011,No Discount,Central,1445.1898
3,Black,Bikes,Mountain Bikes,NaN,1/29/2011,No Discount,Central,10124.9700
4,Silver,Components,Mountain Frames,1204.3248,1/29/2011,No Discount,Central,1445.1898

In [ ]:
df_cleaned.shape

(32040, 8)

## Checking Missing Values

In [ ]:
# counts the number of non-missing (non-null) values in each column
df_cleaned.count()

Color            29073
Category         32040
Subcategory      32040
ListPrice        32032
Orderdate        32040
PromotionName    32040
SalesRegion      32025
SalesAmount      32040
dtype: int64

In [ ]:
# counts total null values in each column
df_cleaned.isnull().sum()

Color            2967
Category            0
Subcategory         0
ListPrice           8
Orderdate           0
PromotionName       0
SalesRegion        15
SalesAmount         0
dtype: int64

In [ ]:
# print every unique label for all text/object columns
text_columns = df_cleaned.select_dtypes(include='object').columns

for col in text_columns:
    print("Column Name:", col)
    print("Unique Labels:", df_cleaned[col].unique(),"\n")

Column Name: Color
Unique Labels: ['Silver' 'Black' 'White' 'Red' 'Multi' 'Blue' nan 'Yellow' 'Silver/Black']

Column Name: Category
Unique Labels: ['Bikes' 'Components' 'Clothing' 'Accessories']

Column Name: Subcategory
Unique Labels: ['Mountain Bikes' 'Mountain Frames' 'Socks' 'Road Frames' 'Jerseys'
 'Road Bikes' 'Caps' 'Helmets' 'Handlebars' 'Wheels' 'Gloves' 'Bib-Shorts'
 'Tights' 'Headsets' 'Forks' 'Pumps' 'Shorts' 'Locks' 'Brakes'
 'Derailleurs' 'Chains' 'Saddles' 'Pedals' 'Cranksets' 'Bottom Brackets'
 'Cleaners' 'Bottles and Cages' 'Hydration Packs' 'Bike Racks' 'Vests'
 'Touring Bikes' 'Touring Frames' 'Tires and Tubes']

Column Name: Orderdate
Unique Labels: ['1/29/2011' '03-01-2011' '3/31/2011' '05-01-2011' '5/31/2011' '1/29/2012'
 '2/29/2012' '3/30/2012' '4/30/2012' '5/30/2012' '6/30/2012' '1/28/2013'
 '2/28/2013' '3/30/2013' '4/30/2013' '5/30/2013' '6/30/2013']

Column Name: PromotionName
Unique Labels: ['No Discount' 'Volume Discount 11 to 14' 'Volume Discount 15 to 24'
 'Volume Discount 25 to 40' 'Road-650 Overstock' 'Touring-3000 Promotion'
 'Touring-1000 Promotion']

Column Name: SalesRegion
Unique Labels: ['Central' nan 'Southeast' 'Canada' 'Northwest' 'Northeast' 'Southwest'
 'United Kingdom' 'France' 'Germany' 'Australia']

We don't have any hidden text placeholders like '?' or 'N/A'. Our data is naturally clean in that aspect. If output shows question marks ('?'), text strings like 'N/A', or blank strings (''), then very first step is to convert them into official system nan markers through np.nan.

In data cleaning step, we only checking the missing values, but the actual handling and replacement of these missing values by actual numerical logical values will be done in later stage data preprocessing.

In [ ]:
# import numpy as np
# df_cleaned = df_cleaned.replace('?',np.nan)

## Fixing Inconsistent Formats

The Orderdate column has an inconsistent format because some rows use forward slashes ('1/29/2011') while other rows use dashes ('03-01-2011')

In [ ]:
df_cleaned['Orderdate'] = pd.to_datetime(df_cleaned['Orderdate'], format='mixed')
# format=mixed: rows in this column contain dates written in different formats, so read and fix each row individually

## Checking Impossible Values

The fastest way to spot impossible numbers across our entire dataset is using df.describe(). This prints a summary table showing the minimum, maximum, and average values for every numeric column.

How to spot an impossible value in the summary:
* Look closely at the min row: If it shows a negative number (e.g., -500), that is impossible.
* Look closely at the max row: If someone accidentally typed an extra zero and made a single order quantity 99999, it will stand out immediately compared to the mean.

In [ ]:
df_cleaned.describe()

          ListPrice                      Orderdate   SalesAmount
count  32032.000000                          32040  32040.000000
mean     714.663419  2012-08-26 13:08:48.539325696   1299.023131
min        2.290000            2011-01-29 00:00:00      1.374000
25%       54.990000            2012-02-29 00:00:00    125.964000
50%      337.220000            2013-01-28 00:00:00    445.410000
75%     1079.990000            2013-03-30 00:00:00   1457.820000
max     3578.270000            2013-06-30 00:00:00  27893.619000
std      851.623778                            NaN   2153.316625

* ListPrice can't be Zero: It is the manufacturer's suggested retail price (the standard sticker price on the shelf). A store does not stock items that officially cost ₹0.00 on the shelf.
* SalesAmount can be Zero: It is the actual money collected at the cash register when a transaction occurs. A transaction total can legitimately be zero. For example, if a customer applies a 100% off coupon, wins a store giveaway, or exchanges a broken item under a warranty, they walk away paying exactly ₹0.00.

In [ ]:
df_cleaned[df_cleaned['ListPrice'] <= 0]

Empty DataFrame
Columns: [Color, Category, Subcategory, ListPrice, Orderdate, PromotionName, SalesRegion, SalesAmount]
Index: []

In [ ]:
df_cleaned[df_cleaned['SalesAmount'] < 0]

Empty DataFrame
Columns: [Color, Category, Subcategory, ListPrice, Orderdate, PromotionName, SalesRegion, SalesAmount]
Index: []

No impossible values present in data but if there then follow below steps.

**Note:** Our target variable is SalesAmount—the exact value our Linear Regression model is trying to learn how to predict. If a row has a negative or missing SalesAmount, we must delete the entire row instead of turning it into a NaN to fill later.

In [ ]:
# 1. Turn 0 or negative ListPrice into NaN
# df_cleaned.loc[df_cleaned['ListPrice'] <= 0, 'ListPrice'] = np.nan

# 2. SalesAmount is our target variable: Drop rows with negative sales completely
# df_cleaned = df_cleaned[df_cleaned['SalesAmount'] >= 0]

# Verify that they are now tracked as true missing values
# print(df_cleaned[['ListPrice', 'SalesAmount']].isnull().sum())

When you want to filter specific rows and columns at the same time to change their values, we must use the .loc accessor. Without .loc, Pandas gets confused trying to read the comma inside the brackets.

## Analysing Data

In [ ]:
df_cleaned.shape

(32040, 8)

In [ ]:
df_cleaned.head()

,Color,Category,Subcategory,ListPrice,Orderdate,PromotionName,SalesRegion,SalesAmount
0,Silver,Bikes,Mountain Bikes,3399.9900,2011-01-29,No Discount,Central,4079.9880
1,Black,Bikes,Mountain Bikes,3374.9900,2011-01-29,No Discount,Central,4049.9880
2,Silver,Components,Mountain Frames,1204.3248,2011-01-29,No Discount,Central,1445.1898
3,Black,Bikes,Mountain Bikes,NaN,2011-01-29,No Discount,Central,10124.9700
4,Silver,Components,Mountain Frames,1204.3248,2011-01-29,No Discount,Central,1445.1898